### ISSUE TITLE
Unparsable negative coefficients

### ISSUE THREAD

**Issue by aryansabet** [mohamedsalahh/Algebraic-Expression-Parser#1]
there is a problem with parsing **negative coefficient**. I think because we consider all `-` as an operator in the parsing process. for example: `(-3)*(x^2)`
```
Traceback (most recent call last):
  File "d:\mine\FF\src\main.py", line 275, in <module>
    main()
  File "d:\mine\FF\src\main.py", line 184, in main
    test = Expression(expression='(-3)*(x^2)', operators=op, operators_info=op_info,
  File "C:\...\Python\Python310\site-packages\AlgebraicExpressionParser\expression\Expression.py", line 32, in __init__
    self._validate()
  File "C:\...\Python\Python310\site-packages\AlgebraicExpressionParser\expression\Expression.py", line 319, in _validate
    self._validate_Expression(self.tokens)
  File "C:\...\Python\Python310\site-packages\AlgebraicExpressionParser\expression\Expression.py", line 274, in _validate_Expression    self._validate_Expression(tokens[i + 1: idx])
  File "C:\...\Python\Python310\site-packages\AlgebraicExpressionParser\expression\Expression.py", line 301, in _validate_Expression    raise InvalidExpressionException(
AlgebraicExpressionParser.exceptions.Exceptions.InvalidExpressionException: (-3)*(x^2) is not a valid expression.
```

**Comment by mohamedsalahh** [comment]
Try it now.
